# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: CapRover Yükleyici

on:
  push:
    branches:
      - master

jobs:
  CapRoverYukleyici:
    name   : KekikStream Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 2

      # Değişiklik Kontrolleri
      - name: Değişiklik Kontrol
        id  : degisiklik
        run : |
          # Stream (services dışındaki dosyalar)
          if git diff --name-only HEAD^ | grep -vE '^services/' | grep -qE '\.(py|txt|j2|html|css|js|json|yaml|yml)$'; then 
            echo "stream=true" >> $GITHUB_OUTPUT
          else 
            echo "stream=false" >> $GITHUB_OUTPUT
          fi

          # Proxy
          if git diff --name-only HEAD^ | grep -qE '^services/proxy/'; then 
            echo "proxy=true" >> $GITHUB_OUTPUT
          else 
            echo "proxy=false" >> $GITHUB_OUTPUT
          fi

          # Socket
          if git diff --name-only HEAD^ | grep -qE '^services/websocket/'; then 
            echo "socket=true" >> $GITHUB_OUTPUT
          else 
            echo "socket=false" >> $GITHUB_OUTPUT
          fi

      # Stream APP (Ana Uygulama)
      - name: Stream TarBall Oluştur
        if  : steps.degisiklik.outputs.stream == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./"
          files  : ./
          outPath: deploy.tar

      - name: Stream APP Deploy
        if  : steps.degisiklik.outputs.stream == 'true'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app   : ${{ secrets.STREAM_APP_NAME }}
          token : ${{ secrets.STREAM_APP_TOKEN }}

      # Proxy APP
      - name: Proxy TarBall Oluştur
        if  : steps.degisiklik.outputs.proxy == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./services/proxy"
          files  : ./
          outPath: deploy.tar

      - name: Proxy APP Deploy
        if  : steps.degisiklik.outputs.proxy == 'true'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app   : ${{ secrets.PROXY_APP_NAME }}
          token : ${{ secrets.PROXY_APP_TOKEN }}

      # WebSocket APP
      - name: Socket TarBall Oluştur
        if  : steps.degisiklik.outputs.socket == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./services/websocket"
          files  : ./
          outPath: deploy.tar

      - name: Socket APP Deploy
        if  : steps.degisiklik.outputs.socket == 'true'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app   : ${{ secrets.SOCKET_APP_NAME }}
          token : ${{ secrets.SOCKET_APP_TOKEN }}
