# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: CapRover Yükleyici

on:
  push:
    branches:
      - master

jobs:
  CapRoverYukleyici:
    name   : KekikStream Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 2

      - name: Güncelleme Kontrol Et
        id  : guncelleme_var_mi
        run : |
          if git diff --name-only HEAD^ | grep -qE '\.(py|txt|j2|html|css|js|json|yaml|yml)$'; then 
            echo "degisiklik=true"
          else 
            echo "degisiklik=false"
          fi >> $GITHUB_OUTPUT

      # Stream APP (Ana Uygulama)
      - name: Stream TarBall Oluştur
        if  : steps.guncelleme_var_mi.outputs.degisiklik == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./"
          files  : ./
          outPath: stream_deploy.tar

      - name: Stream APP Deploy
        if  : steps.guncelleme_var_mi.outputs.degisiklik == 'true'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          tarFile: stream_deploy.tar
          server : ${{ secrets.CAPROVER_SERVER }}
          app    : ${{ secrets.STREAM_APP_NAME }}
          token  : ${{ secrets.STREAM_APP_TOKEN }}

      # Proxy APP
      - name: Proxy TarBall Oluştur
        if  : steps.guncelleme_var_mi.outputs.degisiklik == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./services/proxy"
          files  : ./
          outPath: proxy_deploy.tar

      - name: Proxy APP Deploy
        if  : steps.guncelleme_var_mi.outputs.degisiklik == 'true'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          tarFile: proxy_deploy.tar
          server : ${{ secrets.CAPROVER_SERVER }}
          app    : ${{ secrets.PROXY_APP_NAME }}
          token  : ${{ secrets.PROXY_APP_TOKEN }}

      # WebSocket APP
      - name: Socket TarBall Oluştur
        if  : steps.guncelleme_var_mi.outputs.degisiklik == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./services/websocket"
          files  : ./
          outPath: socket_deploy.tar

      - name: Socket APP Deploy
        if  : steps.guncelleme_var_mi.outputs.degisiklik == 'true'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          tarFile: socket_deploy.tar
          server : ${{ secrets.CAPROVER_SERVER }}
          app    : ${{ secrets.SOCKET_APP_NAME }}
          token  : ${{ secrets.SOCKET_APP_TOKEN }}
